INVENTORY = {
    "Lamborghini": 4,
    "porsche": 3,
    "mercedes benz": 15,
    "bmw": 8,
    "ferrari": 7,
    "range rover": 6,
    "land rover": 6,
    "ford": 38,
    "kia": 28,
    "volkswagen": 5,
    "hyundai": 44,
    "audi": 9,
    "mini": 12,
    "chevrolet": 11,
    "ram": 10,
    "toyota": 12,
    "honda": 19,
    "tesla": 7,
    "jeep": 7,
    "tata": 44,
    "maruti suzuki": 102,
    "mahindra": 25,
}
